#!/usr/bin/bash

if [ -z "$(which git)" ]; then
    echo "Git is not found"
    echo "Please install git via sudo apt install git-all"
    echo "Exiting..."
    exit 1
fi

if [ -z "$(which unbuffer)" ]; then
    echo "Unbuffer is not found"
    echo "Please install unbuffer via sudo apt install expect"
    echo "                         or conda install -c conda-forge expect"
    echo "Exiting..."
    exit 1
fi

if [ -z "$(which inotifywait)" ]; then
    echo "Inotifywait is not found"
    echo "Please install inotifywait via sudo apt install inotify-tools"
    echo "                            or conda install -c conda-forge inotify-tools"
    echo "Exiting..."
    exit 1
fi

if [ ! -f "dgit" ]; then
    echo "Can't find dgit in current directory"
    echo "Please check if you are in dgit repository"
    echo "Exiting..."
    exit 1
fi

echo "Adding dgit to PATH"
echo "export PATH=\$PATH:$(pwd)" >> ~/.bashrc
echo "Done"
